---
# Key Ad Metrices
- name: "Impressions"
  type: line
  label: Timestamp
  visuals:
    borderColor:
      - rgb(75, 192, 192)
    backgroundColor:
      - "rgba(255, 99, 132, 0.2)"
      - "rgba(255, 159, 64, 0.2)"
      - "rgba(255, 205, 86, 0.2)"
      - "rgba(75, 192, 192, 0.2)"
    borderWidth: 1.5
    tension: 0.1
- name: "Clicks"
  type: line
  label: Timestamp
  visuals:
    borderColor:
      - rgba(153, 102, 255, 1)
    borderWidth: 1.5
    tension: 0.1
- name: "CTR%"
  aliases: [CTR (in %)]
  type: bar
  label: Timestamp
  threshold: 0.5
  visuals:
    borderColor:
      - rgb(255, 99, 132)
      - rgb(255, 159, 64)
      - rgb(255, 205, 86)
      - rgb(75, 192, 192)
      - rgb(54, 162, 235)
      - rgb(153, 102, 255)
    backgroundColor:
      - "rgba(255, 99, 132, 0.2)"
      - "rgba(255, 159, 64, 0.2)"
      - "rgba(255, 205, 86, 0.2)"
      - "rgba(75, 192, 192, 0.2)"
      - "rgba(54, 162, 235, 0.2)"
      - "rgba(153, 102, 255, 0.2)"
      - "rgba(201, 203, 207, 0.2)"
    borderWidth: 1.5
    tension: 0.1
- name: "Impressions by Country"
  type: pie
  visuals:
    borderColor:
      - rgb(217 249 157)
      - rgb(255, 99, 132)
      - rgb(255, 159, 64)
      - rgb(255, 205, 86)
      - rgb(75, 192, 192)
      - rgb(54, 162, 235)
      - rgb(153, 102, 255)
      - rgb(201, 203, 207)
    backgroundColor:
      - "#FF6384"
      - "#36A2EB"
      - "#FFCE56"
      - "#4BC0C0"
      - "#9966FF"
      - "#FF9F40"
    hoverOffset: 10
    align: "center"
