import {
  faTachometerAlt,
  faUsers,
  faCog,
  faSignOutAlt,
  faChartBar,
  faFaceSmile,
  faEnvelope,
  faChevronDown,
  faChevronUp,
  faCalendarAlt,
  faTriangleExclamation,
  faSearch,
  faSun,
  faMoon,
  faUserCircle,
  faBell,
  faSliders,
  faChartLine,
  faCalculator,
  faStar,
  faInfoCircle,
  faArrowTrendUp,
  faMaximize,
  faSquareRootVariable,
  faRocket,
  faCloudSunRain,
  faGlobe,
  faPlus,
  faFlag,
  faGauge,
  faFilePdf,
} from "@fortawesome/free-solid-svg-icons";

const ICONS_REGISTRY = Object.freeze({
  NAVICON: faChartBar,
  DASHBOARD: faTachometerAlt,
  USERS: faUsers,
  SETTINGS: faCog,
  SUPPORT: faEnvelope,
  LOGOUT: faSignOutAlt,
  CHEVRON_UP: faChevronUp,
  CHEVRON_DOWN: faChevronDown,
  CALENDER: faCalendarAlt,
  WARNING: faTriangleExclamation,
  SEARCH: faSearch,
  SUN: faSun,
  MOON: faMoon,
  USER_ICON: faUserCircle,
  SLIDERS: faSliders,
  BELL_ICON: faBell,
  CHART_LINE: faChartLine,
  CALCULATOR: faCalculator,
  STAR: faStar,
  INFO_ICON: faInfoCircle,
  ARROW_UP: faArrowTrendUp,
  MAXIMISE: faMaximize,
  SQ_RT: faSquareRootVariable,
  BOOSTER: faRocket,
  SEASON: faCloudSunRain,
  GLOBE: faGlobe,
  GAUGE: faGauge,
  PLUS: faPlus,
  FLAG: faFlag,
  EXPORT_PDF: faFilePdf,
  DEFAULT: faFaceSmile,
});

function getIcon(iconName = "") {
  const icon = iconName.toUpperCase();
  return ICONS_REGISTRY[icon] || ICONS_REGISTRY["DEFAULT"];
}

export default getIcon;
